routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('animal','animal\AnimalController');

app/Models/Animal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Animal extends Model
{
    use HasFactory;

     /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'animal';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    protected $dates = [
		'data_nascimento'
	];

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['nome', 'nome_propietario', 'data_nascimento', 'idade', 'sexo', 'pelagem', 'cor', 'porte'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/animal/AnimalController.php
<?php

namespace App\Http\Controllers\animal;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Animal;

class AnimalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $animais = Animal::all();
        return view('animal.index', [
            'animais' => $animais
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $animais = Animal::all();
        return view('animal.create', [
            'animais' => $animais
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $animal = new Animal();
        $animal->nome = $request->nome;
        $animal->nome_propietario = $request->nome_propietario;
        $animal->data_nascimento = $request->data_nascimento;
        $animal->idade = (intval(date('Y')) - intval(date('Y',strtotime($request->data_nascimento))));
        $animal->sexo = $request->sexo;
        $animal->pelagem = $request->pelagem;
        $animal->cor = $request->cor;
        $animal->porte = $request->porte;
        $animal->save();


        return redirect()->route('animal.index')
                        ->with('status','Animal cadastrado com sucesso.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $animal = Animal::find($id);
        
        return view('animal.show', [
            'animal' => $animal,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $animal = Animal::find($id);
        
        return view('animal.edit', [
            'animal' => $animal,
        ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $animal = Animal::find($id);
        $animal->nome = $request->nome;
        $animal->nome_propietario = $request->nome_propietario;
        $animal->data_nascimento = $request->data_nascimento;
        $animal->idade = (intval(date('Y')) - intval(date('Y',strtotime($request->data_nascimento))));
        $animal->sexo = $request->sexo;
        $animal->pelagem = $request->pelagem;
        $animal->cor = $request->cor;
        $animal->porte = $request->porte;
        $animal->update();

        return redirect()->route('animal.index')
                        ->with('status','Animal alterado com sucesso.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $animal = Animal::find($id);
        $animal->delete();
        
        return redirect()->route('animal.index')
                        ->with('status','Animal removído.');
    }
}

resources/views/animal/create.blade.php
@extends('layouts.app')

@section('content')
        </br>
        <div class="row">
            <div class="col-md-12">
            <div class="card">
                <div class="card-header">Cadastrar animal </div>
                    <div class="card-body">

                        <form action="{{ route('animal.store') }}" method="POST">
                          @csrf

                                <div class="row">
                                    <div class="col-xs-3 col-sm-3 col-md-3">
                                        <label for="nome" class="control-label">{{ 'Nome ' }}</label>
                                        <input class="form-control" name="nome" type="text" id="nome" placeholder="Informe o nome do animal" value="{{ isset($animal->nome) ? $animal->nome : ''}}" required>
                                    </div>
                                    <div class="col-xs-3 col-sm-3 col-md-3">
                                        <label for="nome_propietario" class="control-label">{{ 'Nome propietário' }}</label>
                                        <input class="form-control" name="nome_propietario" type="text" id="nome_propietario" placeholder="Informe o nome do propietário" value="{{ isset($animal->nome_propietario) ? $animal->nome_propietario : ''}}" required>
                                    </div>
                                    <div class="col-xs-3 col-sm-3 col-md-3">
                                        <label for="data_nascimento" class="control-label">{{ 'Data de nascimento ' }}</label>
                                        <input class="form-control" name="data_nascimento" type="date" id="data_nascimento" placeholder="Informe a data de nascimento" value="{{ isset($animal->data_nascimento) ? $animal->data_nascimento : ''}}" >
                                    </div>
                                    <div class="col-xs-2 col-sm-2 col-md-2">
                                        <label for="sexo" class="control-label">{{ 'Sexo' }}</label>
                                        <select name="sexo" class="form-control" id="sexo" required>
                                        @foreach (json_decode('{"M":"Masculino","F":"Feminino"}') as $optionKey => $optionValue)
                                            <option value="{{ $optionKey }}" {{ (isset($animal->sexo) && $animal->sexo == $optionKey) ? 'selected' : ''}}>{{ $optionValue }}</option>
                                        @endforeach
                                    </select>
                                    </div>
                                    <div class="col-xs-3 col-sm-3 col-md-3">
                                        <label for="pelagem" class="control-label">{{ 'Pelagem' }}</label>
                                        <input class="form-control" name="pelagem" type="text" id="pelagem" placeholder="Informe pelagem" value="{{ isset($animal->pelagem) ? $animal->pelagem : ''}}" >
                                    </div>
                                    <div class="col-xs-3 col-sm-3 col-md-3">
                                        <label for="cor" class="control-label">{{ 'Cor' }}</label>
                                        <input class="form-control" name="cor" type="text" id="cor" placeholder="Informe a cor" value="{{ isset($animal->cor) ? $animal->cor : ''}}" >
                                    </div>
                                    <div class="col-xs-3 col-sm-3 col-md-3">
                                        <label for="porte" class="control-label">{{ 'Porte' }}</label>
                                        <input class="form-control" name="porte" type="text" id="porte" placeholder="Informe o porte" value="{{ isset($animal->porte) ? $animal->porte : ''}}" >
                                    </div>

                                   
                                    <div class="col-xs-3 col-sm-3 col-md-4">
                                    </br>
                                    <button type="submit" class="btn btn-primary">
                                        Salvar 
                                    </button>
                                    </div>
                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/animal/edit.blade.php
@extends('layouts.app')

@section('content')
</br>        
        <div class="row">
            <div class="col-md-12">
            <div class="card">
                <div class="card-header">Alterar animal </div>
                    <div class="card-body">
                        <form action="{{ route('animal.update',$animal->id) }}" method="POST">
                            @csrf
                            @method('PUT')

                            <div class="card-body bg-white">

                                    
                            <div class="form-group">
                                        <label for="nome" class="control-label">{{ 'Nome ' }}</label>
                                        <input class="form-control" name="nome" type="text" id="nome" placeholder="Informe o nome do animal" value="{{ isset($animal->nome) ? $animal->nome : ''}}" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="nome_propietario" class="control-label">{{ 'Nome propietário' }}</label>
                                        <input class="form-control" name="nome_propietario" type="text" id="nome_propietario" placeholder="Informe o nome do propietário" value="{{ isset($animal->nome_propietario) ? $animal->nome_propietario : ''}}" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="data_nascimento" class="control-label">{{ 'Data de nascimento ' }}</label>
                                        <input class="form-control" name="data_nascimento" type="date" id="data_nascimento"  value="{{ isset($animal->data_nascimento) ? date('d/m/Y',strtotime($animal->data_nascimento))  : ''}}" >
                                    </div>
                                    <div class="form-group">
                                        <label for="sexo" class="control-label">{{ 'Sexo' }}</label>
                                        <select name="sexo" class="form-control" id="sexo" required>
                                        @foreach (json_decode('{"M":"Masculino","F":"Feminino"}') as $optionKey => $optionValue)
                                            <option value="{{ $optionKey }}" {{ (isset($animal->sexo) && $animal->sexo == $optionKey) ? 'selected' : ''}}>{{ $optionValue }}</option>
                                        @endforeach
                                    </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="pelagem" class="control-label">{{ 'Pelagem' }}</label>
                                        <input class="form-control" name="pelagem" type="text" id="pelagem" placeholder="Informe pelagem" value="{{ isset($animal->pelagem) ? $animal->pelagem : ''}}" >
                                    </div>
                                    <div class="form-group">
                                        <label for="cor" class="control-label">{{ 'Cor' }}</label>
                                        <input class="form-control" name="cor" type="text" id="cor" placeholder="Informe a cor" value="{{ isset($animal->cor) ? $animal->cor : ''}}" >
                                    </div>
                                    <div class="form-group">
                                        <label for="porte" class="control-label">{{ 'Porte' }}</label>
                                        <input class="form-control" name="porte" type="text" id="porte" placeholder="Informe o porte" value="{{ isset($animal->porte) ? $animal->porte : ''}}" >
                                    </div>
                    
                                    <div class="form-group">
                                    <button type="submit" class="btn btn-primary mb-3">
                                        Salvar 
                                    </button>
                                    </div>

                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/animal/index.blade.php
@extends('layouts.app')

@section('content')

<div class="card-body bg-white">
    <div class="container">
        <h1 class="display-4"></h1>
		
		
    </div>
</div>

@if(session()->has('status'))
   <div class="alert alert-primary" role="alert">   
        <p>{{session()->get('status')}}</p>
    </div>
@endif


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="tabela-animais" class="table">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Nome Propietário</th>
                            <th>Data de nascimento</th>
                            <th>Idade (em anos)</th>
                            <th>Sexo</th>
                            <th>Pelagem</th>
                            <th>Cor</th>
                            <th>Porte</th>
                            <th>Opções</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($animais as $animal)
                        <tr>
                            <td>{{ $animal->nome }}</td>
                            <td>{{ $animal->nome_propietario }}</td>
                            <td>{{ date('d/m/Y',strtotime($animal->data_nascimento)) }}</td>
                            <td>{{ $animal->idade }}</td>
                            <td>{{ $animal->sexo }}</td>
                            <td>{{ $animal->pelagem }}</td>
                            <td>{{ $animal->cor }}</td>
                            <td>{{ $animal->porte }}</td>
                            
                            <td>
                                <a href="{{ route('animal.edit',$animal->id) }}" class="btn btn-outline-primary role="button">
                                    Editar
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                    </svg>
                                </a>
                                <form action="{{ route('animal.destroy', $animal->id) }}" method="POST">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button class="btn btn-outline-primary">
                                        Excluir
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bookmark-x-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M4 0a2 2 0 0 0-2 2v13.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4zm2.854 5.146a.5.5 0 1 0-.708.708L7.293 7 6.146 8.146a.5.5 0 1 0 .708.708L8 7.707l1.146 1.147a.5.5 0 1 0 .708-.708L8.707 7l1.147-1.146a.5.5 0 0 0-.708-.708L8 6.293 6.854 5.146z"/>
                                        </svg>
                                    </button>
                                </form>

        
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <a href="{{ route('animal.create') }}" title="Placeholder link title" class="text-decoration-none">
                Cadastrar animal
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bookmark-plus-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M4 0a2 2 0 0 0-2 2v13.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4zm4.5 4.5a.5.5 0 0 0-1 0V6H6a.5.5 0 0 0 0 1h1.5v1.5a.5.5 0 0 0 1 0V7H10a.5.5 0 0 0 0-1H8.5V4.5z"/>
                </svg>
                </a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/animal/show.blade.php
@extends('layouts.app')

@section('content')
</br>

    <div class="container">
        <div class="row">

            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Jogador </div>
                    <div class="card-body">
                        <br/>

                        <div class="table-responsive col-md-12">
                            <table class="table">
                                <tbody>
                                    <tr><th> Nome </th>
									<td> {{ $jogador->nome }} </td>
									</tr>
									<tr>
									<th> Nível </th>
									<td> {{ $jogador->nivel }} </td>
									</tr>
                                    <th> Goleiro </th>
									<td> 
                                    @if ($jogador->goleiro ==1) 
                                        Sim 
                                    @else
                                        Não 
                                    @endif 
                                    </td>
									</tr>
									<tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Registro de Animais') }}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    

	
</head>
<body>

    <div class="container">	

    
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand" href="{{ route('animal.index')}}">Registro de Animais</a>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                </ul>
            </div>
        </nav>
  
		@yield('content')
	</div>


    <script src="{{ asset('/componentes/js/app.js') }}"></script>
    <script src="{{ asset('/componentes/js/alert.js') }}"></script>
    <script src="{{ asset('/componentes/js/bootstrap.js') }}"></script>
    <script src="{{ asset('/componentes/js/button.js') }}"></script>
    <script src="{{ asset('/componentes/js/carousel.js') }}"></script>
    <script src="{{ asset('/componentes/js/collapse.js') }}"></script>
    <script src="{{ asset('/componentes/js/dropdown.js') }}"></script>
    <script src="{{ asset('/componentes/js/index.js') }}"></script>
    <script src="{{ asset('/componentes/js/modal.js') }}"></script>
    <script src="{{ asset('/componentes/js/popover.js') }}"></script>
    <script src="{{ asset('/componentes/js/bootstrap.bundle.js') }}"></script>
    <script src="{{ asset('/componentes/js/scrollspy.js') }}"></script>
    <script src="{{ asset('/componentes/js/tab.js') }}"></script>
    <script src="{{ asset('/componentes/js/tooltip.js') }}"></script>
    <script src="{{ asset('/componentes/js/util.js') }}"></script>
    <script src="{{ asset('/componentes/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('/componentes/js/bootstrap.min.js') }}"></script>
    

</body>
</html>